<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ProductsSach;
use App\Models\Category;

class FinalBooksSeeder extends Seeder
{
    public function run()
    {
        $sachCategory = Category::where('slug', 'sach-trego')->first();

        $finalBooks = [
            [
                'title' => 'Tôi Tài Giỏi, Bạn Cũng Thế!',
                'slug' => 'toi-tai-gioi-ban-cung-the',
                'description' => 'Adam Khoo chia sẻ những bí quyết học tập hiệu quả và phát triển trí thông minh.',
                'short_description' => 'Phương pháp học tập hiệu quả',
                'isbn' => '978-604-2-11234-5',
                'sku' => 'SACH-TTG-007',
                'price' => 98000,
                'sale_price' => 79000,
                'stock_quantity' => 75,
                'author' => 'Adam Khoo',
                'translator' => 'Nguyễn Thành Nam',
                'publisher' => 'NXB Tổng Hợp TPHCM',
                'publication_date' => '2020-08-12',
                'language' => 'vi',
                'pages' => 280,
                'format' => 'Bìa mềm',
                'dimensions' => '19 x 13 cm',
                'weight' => 310.0,
                'category_id' => $sachCategory->id,
                'genres' => ['Kỹ năng sống', 'Giáo dục'],
                'keywords' => ['học tập', 'trí nhớ'],
                'images' => ['/images/books/toi-tai-gioi.jpg'],
                'status' => 'active',
                'featured' => false,
                'bestseller' => true,
                'new_release' => false
            ],
            [
                'title' => 'Người Bán Hàng Vĩ Đại Nhất Thế Giới',
                'slug' => 'nguoi-ban-hang-vi-dai-nhat',
                'description' => 'Og Mandino kể câu chuyện về 10 cuộn giấy da chứa bí quyết bán hàng.',
                'short_description' => '10 bí quyết bán hàng từ thương gia vĩ đại',
                'isbn' => '978-604-2-18765-2',
                'sku' => 'SACH-NBH-008',
                'price' => 109000,
                'sale_price' => 89000,
                'stock_quantity' => 67,
                'author' => 'Og Mandino',
                'translator' => 'Nguyễn Thị Phương',
                'publisher' => 'NXB Thương Mại',
                'publication_date' => '2020-10-08',
                'language' => 'vi',
                'pages' => 352,
                'format' => 'Bìa mềm',
                'dimensions' => '19 x 13 cm',
                'weight' => 380.0,
                'category_id' => $sachCategory->id,
                'genres' => ['Kinh doanh', 'Bán hàng'],
                'keywords' => ['bán hàng', 'kinh doanh'],
                'images' => ['/images/books/nguoi-ban-hang.jpg'],
                'status' => 'active',
                'featured' => false,
                'bestseller' => false,
                'new_release' => false
            ],
            [
                'title' => 'Quẳng Gánh Lo Đi Và Vui Sống',
                'slug' => 'quang-ganh-lo-di-va-vui-song',
                'description' => 'Dale Carnegie hướng dẫn cách vượt qua lo lắng và sống một cuộc đời hạnh phúc.',
                'short_description' => 'Nghệ thuật sống hạnh phúc không lo lắng',
                'isbn' => '978-604-2-19876-4',
                'sku' => 'SACH-QGL-009',
                'price' => 85000,
                'sale_price' => 69000,
                'stock_quantity' => 90,
                'author' => 'Dale Carnegie',
                'translator' => 'Nguyễn Thị Hoa',
                'publisher' => 'NXB Tổng Hợp TPHCM',
                'publication_date' => '2019-06-20',
                'language' => 'vi',
                'pages' => 312,
                'format' => 'Bìa mềm',
                'dimensions' => '19 x 13 cm',
                'weight' => 340.0,
                'category_id' => $sachCategory->id,
                'genres' => ['Kỹ năng sống', 'Tâm lý học'],
                'keywords' => ['hạnh phúc', 'lo lắng'],
                'images' => ['/images/books/quang-ganh-lo.jpg'],
                'status' => 'active',
                'featured' => true,
                'bestseller' => true,
                'new_release' => false
            ],
            [
                'title' => 'Không Ai Cứu Được Bạn Ngoại Trừ Chính Bạn',
                'slug' => 'khong-ai-cuu-duoc-ban',
                'description' => 'Những lời khuyên thực tế về tự cứu mình và xây dựng cuộc sống theo ý muốn.',
                'short_description' => 'Tự cứu bản thân và thay đổi cuộc đời',
                'isbn' => '978-604-2-20987-6',
                'sku' => 'SACH-KAC-010',
                'price' => 79000,
                'sale_price' => null,
                'stock_quantity' => 110,
                'author' => 'Brianna Wiest',
                'translator' => 'Nguyễn Minh Châu',
                'publisher' => 'NXB Phụ Nữ',
                'publication_date' => '2022-05-10',
                'language' => 'vi',
                'pages' => 268,
                'format' => 'Bìa mềm',
                'dimensions' => '20 x 14 cm',
                'weight' => 290.0,
                'category_id' => $sachCategory->id,
                'genres' => ['Tự phát triển', 'Tâm lý học'],
                'keywords' => ['tự cứu', 'thay đổi'],
                'images' => ['/images/books/khong-ai-cuu.jpg'],
                'status' => 'active',
                'featured' => false,
                'bestseller' => true,
                'new_release' => true
            ],
            [
                'title' => 'Hành Trình Về Phương Đông',
                'slug' => 'hanh-trinh-ve-phuong-dong',
                'description' => 'Nguyên Phong kể về hành trình tìm hiểu triết lý phương Đông và ý nghĩa cuộc sống.',
                'short_description' => 'Khám phá triết lý và văn hóa phương Đông',
                'isbn' => '978-604-2-21098-7',
                'sku' => 'SACH-HTV-011',
                'price' => 95000,
                'sale_price' => 79000,
                'stock_quantity' => 85,
                'author' => 'Nguyên Phong',
                'translator' => null,
                'publisher' => 'NXB Tôn Giáo',
                'publication_date' => '2018-11-15',
                'language' => 'vi',
                'pages' => 384,
                'format' => 'Bìa mềm',
                'dimensions' => '20 x 14 cm',
                'weight' => 420.0,
                'category_id' => $sachCategory->id,
                'genres' => ['Triết học', 'Tâm linh'],
                'keywords' => ['phương đông', 'triết lý'],
                'images' => ['/images/books/hanh-trinh-phuong-dong.jpg'],
                'status' => 'active',
                'featured' => true,
                'bestseller' => false,
                'new_release' => false
            ],
            [
                'title' => 'Cafe Cùng Tony',
                'slug' => 'cafe-cung-tony',
                'description' => 'Tony Buổi Sáng chia sẻ những câu chuyện về cuộc sống, kinh doanh và khởi nghiệp.',
                'short_description' => 'Những câu chuyện về kinh doanh và cuộc sống',
                'isbn' => '978-604-2-22109-8',
                'sku' => 'SACH-CCT-012',
                'price' => 89000,
                'sale_price' => 75000,
                'stock_quantity' => 95,
                'author' => 'Tony Buổi Sáng',
                'translator' => null,
                'publisher' => 'NXB Trẻ',
                'publication_date' => '2021-08-25',
                'language' => 'vi',
                'pages' => 296,
                'format' => 'Bìa mềm',
                'dimensions' => '19 x 13 cm',
                'weight' => 320.0,
                'category_id' => $sachCategory->id,
                'genres' => ['Kinh doanh', 'Khởi nghiệp'],
                'keywords' => ['khởi nghiệp', 'câu chuyện'],
                'images' => ['/images/books/cafe-cung-tony.jpg'],
                'status' => 'active',
                'featured' => false,
                'bestseller' => true,
                'new_release' => false
            ]
        ];

        foreach ($finalBooks as $book) {
            ProductsSach::create($book);
        }
    }
}